### ISSUE TITLE
2023夏令营

### ISSUE THREAD

**Issue by plmokm1** [LinghaoChan/CSSummerCamp2022#103]
请问博主2023夏令营还会收集信息以这样的形式放出来吗？

**Comment by aisingeoroclan** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by plmokm1** [comment]
这是来自QQ邮箱的假期自动回复邮件。你运气不怎么样。

**Comment by LinghaoChan** [comment]
Yes. Please refer to this [repo](https://github.com/CS-BAOYAN/CSSummerCamp2023).
