### ISSUE TITLE
【借坑】安利一下按时间排序的夏令营列表

### ISSUE THREAD

**Issue by icy-blue** [LinghaoChan/CSSummerCamp2022#94]
[Ordered_CSSummerCamp2022](https://github.com/kvrmnks/Ordered_CSSummerCamp2022)

同学的项目，写了一个python脚本，每小时自动从本仓库同步，区分每个夏令营是否过期，并按照时间排序

祝大家夏令营面试~鸽学校~愉快！

**Comment by LinghaoChan** [comment]
夏令营基本上结束了，我将这个issue关了～

**Comment by Baxkiller** [comment]
（自动回复）信件已经收到，谢谢您！祝好！

**Comment by aisingeoroclan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
